version: '3'
services:
  data_collector:
    build: .
    image: data_collector:latest
    restart: always
    volumes:
      - ./app:/app
    depends_on:
      - clickhouse
    command: python3 -u ./data_collector.py

  data_quality_check:
    build: .
    image: data_quality_check:latest
    restart: always
    volumes:
      - ./app:/app
    depends_on:
      - clickhouse
    command: python3 -u ./data_quality_check.py

  load_history:
    build: .
    image: load_history:latest
    #restart: always
    volumes:
      - ./app:/app
    depends_on:
      - clickhouse
    command: python3 -u ./load_history.py

  clickhouse:
    image: yandex/clickhouse-server
    restart: always
    ports:
      - "8123:8123"  # Измените порт на хосте, если 8124 уже занят
      - "9001:9000"
    volumes:
      - ./data:/var/lib/clickhouse
      - ./config/users.xml:/etc/clickhouse-server/users.xml
    env_file:
      - ./config/clickhouse.env